backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:

  - name: "posts"
    label: "投稿"

    files:

      - name: "diary"
        label: "日記"
        file: "data/diary.json"
        format: "json"

        fields:

          - label: "日記一覧"
            name: "posts"
            widget: "list"

            fields:

              - label: "日付"
                name: "date"
                widget: "string"

              - label: "タイトル"
                name: "title"
                widget: "string"

              - label: "本文"
                name: "body"
                widget: "text"


      - name: "urabanashi"
        label: "裏話"
        file: "data/urabanashi.json"
        format: "json"

        fields:

          - label: "裏話一覧"
            name: "posts"
            widget: "list"

            fields:

              - label: "日付"
                name: "date"
                widget: "string"

              - label: "タイトル"
                name: "title"
                widget: "string"

              - label: "本文"
                name: "body"
                widget: "text"