backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:

  - name: "posts"
    label: "投稿"

    files:

      - name: "diary"
        label: "日記"
        file: "data/diary.json"
        format: "json"

        fields:

          - label: "日記一覧"
            name: "posts"
            widget: "list"

            fields:

              - label: "日付"
                name: "date"
                widget: "string"

              - label: "タイトル"
                name: "title"
                widget: "string"

              - label: "内容"
                name: "blocks"
                widget: "list"
                types:

                  - label: "📝 文章"
                    name: "text"
                    widget: "object"
                    fields:

                      - label: "文章"
                        name: "text"
                        widget: "text"


                  - label: "🖼 画像"
                    name: "image"
                    widget: "object"
                    fields:

                      - label: "画像"
                        name: "image"
                        widget: "image"


                  - label: "🖼📝 画像左＋文章右"
                    name: "image_left"
                    widget: "object"
                    fields:

                      - label: "画像"
                        name: "image"
                        widget: "image"

                      - label: "文章"
                        name: "text"
                        widget: "text"


                  - label: "📝🖼 文章左＋画像右"
                    name: "image_right"
                    widget: "object"
                    fields:

                      - label: "文章"
                        name: "text"
                        widget: "text"

                      - label: "画像"
                        name: "image"
                        widget: "image"


                  - label: "🖼🖼 画像2枚横並び"
                    name: "two_images"
                    widget: "object"
                    fields:

                      - label: "左の画像"
                        name: "image1"
                        widget: "image"

                      - label: "右の画像"
                        name: "image2"
                        widget: "image"